### ISSUE TITLE
Is there any support for connecting to MySql via SSL?

### ISSUE THREAD

**Issue by rob7429** [byjg/migration#10]
Thanks in advance for a response.

**Comment by byjg** [comment]
Hi Rob!

Until now we not implemented SSL connection. The connection part is done by the "byjg/anydataset" component. I can implement the solution on this component but I still need a real case for test. Can you do that for me?

If you can help me I'll open an issue on the "byjg/anydataset" and mark you there and start the implementation .

**Comment by rob7429** [comment]
Sounds great. Yes indeed, I can absolutely be a real test case for you.
Let's do it!!

Thanks

**Comment by byjg** [comment]
Good to know!

I opened the issue: https://github.com/byjg/anydataset/issues/5. Please follow it. I'll notify the changes there.

**Comment by byjg** [comment]
Done. Could you test it?

**Comment by byjg** [comment]
Support added. Just `composer update` and use this connection:

```
mysql://user:password@server/schema?ca=/path/ca&key=/path/sslkey&cert=/path/sslcert&verifyssl=false
```
