### ISSUE TITLE
Symfony/console 4 support

### ISSUE THREAD

**Issue by mstrouhal** [byjg/migration#16]
Hello @byjg , thank you for great library!
I have a question - is there any chance of upgrading or adding version constraint of `symfony/console` 
 dependency to ^4.0 in addition to current ^3.1?

Thank you for your response,
Martin

**Comment by byjg** [comment]
Thank you !

I upgraded recently all my libraries and it is a good opportunity to upgrade the symfony as well. However if I upgrade for Symfony/console 4.0 I will lost support for PHP 7.0 and PHP 5.6. I know both versions wont be upgrade after next month but there a lot of people still using it. (Here the broken test --  https://travis-ci.org/byjg/migration/builds/459307900)

One thing I can do is split the project in different parts. One part will have only the library and another part will have only the CLI and the Symfony/Console. 

This is fast and If I go in this way probably this week I'll finish this.

**Comment by byjg** [comment]
I opened two PR for this:
- https://github.com/byjg/migration/pull/17
- https://github.com/byjg/migration-cli/pull/1

Take a look on it. I will merge it this week.

**Comment by mstrouhal** [comment]
Wow, I did not expect so quick reaction! Those pull requests are looking good, they are doing exactly what they should. 
Splitting the library will enable easy integration into projects already using `symfony\console` without forcing them to use older version. Thank you for everything, @byjg !

**Comment by byjg** [comment]
Merged #17
