### ISSUE TITLE
Universal migration method and support for PostgreSQL databases with additional schemas

### ISSUE THREAD

**Issue by Furgas** [byjg/migration#18]
Thanks for the library.

My use case:
- default PostgreSQL cluster installation (user and database `postgres`) and already created additional user for my application with CREATEDB privilege (there is no database named after the user)
- my application database has schema (or schemas) other than `public`
- I want one universal migration script (that is, it should reset the database if it is not present, or update it if it is present)

The default `PgsqlDatabase` class and `Migration::update()` is not capable of supporting this use case, so I extended `PgsqlDatabase` class and prepared my own migration method. Maybe it will be of some use to someone, or maybe it will inspire some changes in the library.

My `PgsqlDatabase` implementation:
```php
use ByJG\AnyDataset\Db\Factory;
use ByJG\DbMigration\Database\PgsqlDatabase;
use ByJG\Util\Uri;
use Psr\Http\Message\UriInterface;

class MyPgsqlDatabase extends PgsqlDatabase {

	/**
	 * Reasons for overriding:
	 * - Overriding getDbDriverWithoutDatabase won't work because original prepareEnvironment 
	 *   method uses self:: not static:: calls.
	 */
	public static function prepareEnvironment(UriInterface $uri): void {
		$database = preg_replace('~^/~', '', $uri->getPath());
		$dbDriver = static::getDbDriverWithoutDatabase($uri);
		static::createDatabaseIfNotExists($dbDriver, $database);
	}

	/**
	 * Reasons for overriding:
	 * - PDO will try to connect to database with the same name as the user, but I don't have 
	 *   such database. Connect to the default "postgres" database instead.
	 */
	protected static function getDbDriverWithoutDatabase(UriInterface $uri) {
		$customUri = new Uri($uri->__toString());

		return Factory::getDbRelationalInstance($customUri->withPath('/postgres')->__toString());
	}

	/**
	 * Reasons for overriding:
	 * - In case of $versionInfo['version'] === 0 the empty() method will return true, so the
	 *   second row will be created. Use === false instead - that's the value when there is
	 *   no version row.
	 */
	protected function checkExistsVersion(): void {
		$versionInfo = $this->getVersion();
		if ($versionInfo['version'] === false) {
			$this->getDbDriver()->execute(
				sprintf(
					"insert into %s values(0, 'unknow')",
					$this->getMigrationTable()
				)
			);
		}
	}

	/**
	 * Reasons for overriding:
	 * - I'm using "public" schema only for migration table. My applications use other schema 
	 *   or even multiple schemas.
	 */
	public function dropDatabase(): void {
		// drop all non-standqard schemas
		$iterator = $this->getDbDriver()->getIterator(
			"select distinct 'drop schema if exists \"'|| schemaname || '\" cascade;' command from pg_tables where schemaname not in ('public', 'pg_catalog', 'information_schema');"
		);
		foreach ($iterator as $singleRow) {
			$this->getDbDriver()->execute($singleRow->get('command'));
		}

		// then drop all tables from public schema
		parent::dropDatabase();
	}
}
```

My universal migration implementation:
```php
function migratePgsqlDatabase(UriInterface $uri, string $folder): void {
	$migration = new Migration(
		$uri,
		$folder,
		true,
		'public.migration_version' // store migration table in public schema
	);

	$migration->registerDatabase('pgsql', MyPgsqlDatabase::class);

	$migration->prepareEnvironment();
	$migration->createVersion();
	$version = $migration->getCurrentVersion();

	// is there any better way to check if any script (base or migration) was executed before?
	// also why 'unknow' and not 'unknown'?
	if ($version['version'] === 0 && $version['status'] === 'unknow') {
		$migration->reset();
	}
	else {
		$migration->update();
	}
}
```

**Comment by byjg** [comment]
Hello, 

Thank you for your suggestions! I implemented most of them in the temporary composer version `4.0.2.x-dev` (https://github.com/byjg/migration/compare/4.0.2?expand=1)

Below some comments about your contribution:

- `MyPgsqlDatabase::prepareEnvironment`: I followed your recomendation and use static. Thanks.
- `MyPgsqlDatabase::checkExistsVersion`: Thank you for report a bug and the patch. I implemented and create a UnitTest for that. 
- `MyPgsqlDatabase::getDbDriverWithoutDatabase`: I did not understand very well why you needed to customize this because you already defined the migration table to `public.migration_version`. You could just set the URI with the correct database, dont you?
- `MyPsqlDatabase::dropDatabase`: As you have a specific scenario, makes sense to me you override the class.

**Comment by Furgas** [comment]
The reason for changing `getDbDriverWithoutDatabase()` is not about migration table. Without the change the failing scenario is:
- initial state: PostgreSQL cluster only with user `postgres`, database `postgres` and user `myapp_user` (no other databases especially no `myapp_user` database)
- my URI is: `pgsql://myapp_user:password@localhost/myapp_database`
- my universal migration script is always calling `prepareEnvironment` to create the `myapp_database` if it doesn't exist
- original `getDbDriverWithoutDatabase` connects to URI `pgsql://myapp_user:password@localhost/` but when you don't provide database name, the PDO tries to connect to the database with the same name as the user, but there is no `myapp_user` database so it fails

This is why I'm using `pgsql://myapp_user:password@localhost/postgres` URI in my `getDbDriverWithoutDatabase` - the `postgres` database is guaranteed to exist (at least in my installations).

**Comment by Furgas** [comment]
Non-standard schemas are always my app's schemas so it's safe to drop them all. I'm droping whole schemas and not only tables because there can be objects not directly connected with tables (ex. functions/procedures, types etc.) and they won't be deleted by your original code.

**Comment by byjg** [comment]
I understood. However functions, procedures, types, etc should be managed by the migration scripts. In fact, your developers (and you) should never access the Live Database anymore. This way you don't have to take care about this schemas. 

But If it is really, really necessary I can add to the Connection URI an option like : `?dropallschemas=true` (or something else).

**Comment by Furgas** [comment]
You don't have to change that. I'm perfectly fine with making my own implementation by overriding the dropDatabase method. My base.sql is creating these schemas so it just makes sense to drop them all.

**Comment by Furgas** [comment]
It seems so.

I'll test it tomorrow and get back to you.

**Comment by Furgas** [comment]
One more thing maybe. I would move `const INITIAL_STATE` to Migration clase, rename it to `VERSION_STATUS_INITIAL` (or `VERSION_STATUS_UNKNOWN`) and also add consts for the other two: `VERSION_STATUS_PARTIAL` and `VERSION_STATUS_COMPLETE`.

**Comment by byjg** [comment]
Totally makes sense. It is done!

**Comment by Furgas** [comment]
Ok, I've managed to test it now. Works great.

**Comment by byjg** [comment]
Merged. Created the version 4.0.2
