### ISSUE TITLE
migrate is not recognized

### ISSUE THREAD

**Issue by andrehendrata** [byjg/migration#34]
Hi, Im really new to this
I've tried to install composer require "byjg/migration":"4.2.*"

and tried to run command migrate, the result is migrate not recognized

![image](https://user-images.githubusercontent.com/5380515/106796677-44c3bd80-668e-11eb-8d39-1e8a4f2d3191.png)

maybe something missing?
the same issue with vendor command and others

**Comment by byjg** [comment]
I am closing this issue and moving the discussion to https://github.com/byjg/migration-cli/issues/8.
