### ISSUE TITLE
php 8 compatibility

### ISSUE THREAD

**Issue by M1keSK** [byjg/migration#41]
I am using php version 8.1.3 with example from documents on mysql

```
// Create the Connection URI
// See more: https://github.com/byjg/anydataset#connection-based-on-uri
$uriString = 'mysql://' . $dbUser . ':' . $dbPass . '@' . $dbHost . ':' . $dbPort . '/' . $dbName;
$connectionUri = new \ByJG\Util\Uri($uriString);

// Create the Migration instance
$migration = new \ByJG\DbMigration\Migration($connectionUri, './resources', false);

// Register the Database or Databases can handle that URI:
$migration->registerDatabase('mysql', \ByJG\DbMigration\Database\MySqlDatabase::class);
$migration->registerDatabase('maria', \ByJG\DbMigration\Database\MySqlDatabase::class);

$migration->reset();
```

I got these warnings:

> PHP Deprecated:  parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/byjg/uri/src/Uri.php on line 118
> Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /var/www/html/vendor/byjg/uri/src/Uri.php on line 125

I tested this on 7.4 & 7.3 with no warnings

**Comment by byjg** [comment]
I created a PR for the project URI, where the error is thrown. 

Could you validate it?

Thanks.

**Comment by M1keSK** [comment]
Those warnings are fixed, however this new one appears
`PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /var/www/html/vendor/byjg/migration/src/Migration.php on line 187`

issue appears when migrating up or reset (with up)

**Comment by byjg** [comment]
All right. I merged the URI project, so you can restore your composer JSON and the next update will get the correct one. 

I'll take a look at this error.

**Comment by M1keSK** [comment]
```
require __DIR__ . '/vendor/autoload.php';

$dbHost = 'mysql'; // name of mysql container
$dbName = 'project';
$dbPort = 3306;
$dbUser = 'user';
$dbPass = 'pass';

$uriString = 'mysql://' . $dbUser . ':' . $dbPass . '@' . $dbHost . ':' . $dbPort . '/' . $dbName;
$connectionUri = new \ByJG\Util\Uri($uriString);

$migration = new \ByJG\DbMigration\Migration($connectionUri, './resources', false);
$migration->registerDatabase('mysql', \ByJG\DbMigration\Database\MySqlDatabase::class);
$migration->registerDatabase('maria', \ByJG\DbMigration\Database\MySqlDatabase::class);

$migration->reset();
```

**Comment by byjg** [comment]
Found the issue and fixed it in branch 4.2.1.

You can change your composer to use `4.2.1.x-dev` 

Let me know if it fixes, so I can create a new release with this.

**Comment by M1keSK** [comment]
seems to be fixed

**Comment by byjg** [comment]
OK. PR merged. 

Release 4.2.2 created. 

I am closing this issue.
